name: Lint and Test

on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+.x'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'

      - name: Check if formatting is necessary
        run: |
          test -z $(gofmt -l -s .)

      - name: Install linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.39.0

      - name: Lint code
        run: cd v2 && ../bin/golangci-lint run

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'

      - name: Run tests
        # Exclude example code from coverage
        run: cd v2 && go test -coverpkg=./... -coverprofile=coverage.out $(go list ./...)

      - name: Upload coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: v2/coverage.out
